### ISSUE TITLE
Request for information

### ISSUE THREAD

**Issue by peacefulwind777** [x64architecture/wnmp#126]
Dear Sir,

I discovered your wnmp project last week and I took a great deal of pleasure to use it. I would like use to it with my production server but I wanted to ask you something before : Would you like to continue this project in the future ?

Thank you for considering my request.
I look forward to hearing from you.

Sincerely,

**Comment by x64architecture** [comment]
This isn't for production use, at least out of the box. Nginx on Windows can't handle production loads as well.
