### ISSUE TITLE
Code Bug Report 

### ISSUE THREAD

**Issue by ugksoft123** [x64architecture/wnmp#131]
### 1.php.cs

+                for (var i = 1; i <= ProcessCount; i++)
+                {

                    StartProcess(ExeFileName, $"-b localhost:{port} -c {phpini}", false, env_vars);
                    Log.Notice("Starting PHP " + i + "/" + ProcessCount, ProgLogSection);
+                    port = (ushort)(port + 1);
+                }

### 2.OptionsFrm.cs
 ushort port = (ushort)PHP_PORT.Value;
+                for (var i = 0; i < PHPProcesses; i++)
+                {
                    sw.WriteLine("    server 127.0.0.1:" + port + " weight=1;");
+                    port = (ushort)(port + 1);
+                }

**Comment by x64architecture** [comment]
I'm not sure what you are saying the issue is but Wnmp launches multiple PHP instances on a single port by utilizing the `ReuseAddress` socket option.
